#!/bin/sh
kpropd=/usr/sbin/kpropd
if ! test -f /var/kerberos/krb5kdc/kpropd.acl ; then
	echo $"Error. This does not appear to be a slave server, kpropd.acl not found"
	exit 6
fi
if ! test -x "$kpropd" ; then
	exit 5
fi
exec "$kpropd" "$@"
